Vagrant.require_version ">=1.6.0"
VAGRANT_API_VERSION = "2"

require 'yaml'

servers = YAML.load_file('servers.yaml')

Vagrant.configure(VAGRANT_API_VERSION) do |config|
  servers.each do |servers|
    config.vm.define servers["name"] do |srv|
      srv.vm.box = servers["box"]
      srv.vm.box_url = servers["box_url"]
      srv.vm.hostname = servers["hostname"]
      srv.vm.network "private_network", ip: servers["ip"]
      srv.vm.provider :virtualbox do |vb|
        vb.name = servers["name"]
        vb.memory = servers["ram"]
      end
      srv.vm.provision "shell", path: servers["shell"], args: servers["name"] 
    end
  end
end
